[build-system]
requires = ["setuptools==84.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "minerva-deck"
version = "1.0.2"
description = "Desktop client for searching and selectively downloading from MiNERVA"
requires-python = "==3.12.*"
dependencies = [
  "PySide6==6.11.2",
  "libarchive-c==5.3",
  "libtorrent==2.1.1",
]

[project.optional-dependencies]
build = [
  "Nuitka==4.2",
  "ordered-set==4.1.0",
  "zstandard==0.25.0",
]

[tool.setuptools]
packages = ["minerva_app"]
